name: Build Executables

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Compress executable
      run: |
        tar -czvf executable.tar.gz -C dist/ .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: executable.tar.gz
