name: Build Executables

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable (Linux2004)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Build executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Compress executable (Linux2004)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        tar -czvf ubuntu-2004.tar.gz -C dist/ .

    - name: Compress executable (Linux-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        tar -czvf ubuntu-latest.tar.gz -C dist/ .

    - name: Upload artifact (Linux2004)
      if: matrix.os == 'ubuntu-20.04'
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: ubuntu-2004.tar.gz

    - name: Upload artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: ubuntu-latest.tar.gz

    - name: Upload artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/main.exe

    - name: Upload artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/main
